var searchData=
[
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['../classcoral_1_1bus_1_1_variable_subscriber.html#a17008647b1edfd610f6719d5c62a064f',1,'coral::bus::VariableSubscriber::Value()'],['../classcoral_1_1model_1_1_variable_setting.html#a7f8cddb60b09b5dc640230815373327b',1,'coral::model::VariableSetting::Value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['variability',['Variability',['../classcoral_1_1model_1_1_variable_description.html#a29e126ca6eeaf692b675b302e3647094',1,'coral::model::VariableDescription']]],
  ['variable',['Variable',['../classcoral_1_1model_1_1_slave_type_description.html#af192152d895fff061af6e4a6d579102c',1,'coral::model::SlaveTypeDescription::Variable()'],['../classcoral_1_1model_1_1_variable_setting.html#ae5b13f7b07392a763c999b171ab16962',1,'coral::model::VariableSetting::Variable()']]],
  ['variablepublisher',['VariablePublisher',['../classcoral_1_1bus_1_1_variable_publisher.html#a4ff5d1da4b8f015e877188b7b15a516f',1,'coral::bus::VariablePublisher']]],
  ['variables',['Variables',['../classcoral_1_1model_1_1_slave_type_description.html#a0a9c9569499c4d77a7142b956ddd7e01',1,'coral::model::SlaveTypeDescription']]],
  ['variablesetting',['VariableSetting',['../classcoral_1_1model_1_1_variable_setting.html#a68b6d6425c5aeca3b2cfd379721b4aad',1,'coral::model::VariableSetting::VariableSetting(VariableID variable, const ScalarValue &amp;value)'],['../classcoral_1_1model_1_1_variable_setting.html#ac8da204e837aba5ae45d940d2b37fa6d',1,'coral::model::VariableSetting::VariableSetting(VariableID inputVar, const coral::model::Variable &amp;outputVar)'],['../classcoral_1_1model_1_1_variable_setting.html#ac2287eaa11b03909d725eb869d67d88c',1,'coral::model::VariableSetting::VariableSetting(VariableID inputVar, const ScalarValue &amp;value, const coral::model::Variable &amp;outputVar)']]],
  ['variablesubscriber',['VariableSubscriber',['../classcoral_1_1bus_1_1_variable_subscriber.html#a54652e49799f6a7910ac38c357a58394',1,'coral::bus::VariableSubscriber']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector']]],
  ['version',['Version',['../classcoral_1_1model_1_1_slave_type_description.html#ab4e6609ce9c1a5891300b3c83155a727',1,'coral::model::SlaveTypeDescription']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
