var searchData=
[
  ['v1_5f0',['v1_0',['../namespacecoral_1_1fmi.html#a15c5afb4b7dfd27ccccc718316d4a0eca09d7da9ea375f1827517b45b61cfc6b8',1,'coral::fmi']]],
  ['v2_5f0',['v2_0',['../namespacecoral_1_1fmi.html#a15c5afb4b7dfd27ccccc718316d4a0eca5f1bc491eaa9f559d81eabb8182eb2d6',1,'coral::fmi']]],
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['value',['Value',['../classcoral_1_1bus_1_1_variable_subscriber.html#a17008647b1edfd610f6719d5c62a064f',1,'coral::bus::VariableSubscriber::Value()'],['../classcoral_1_1model_1_1_variable_setting.html#a7f8cddb60b09b5dc640230815373327b',1,'coral::model::VariableSetting::Value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['variability',['Variability',['../classcoral_1_1model_1_1_variable_description.html#a29e126ca6eeaf692b675b302e3647094',1,'coral::model::VariableDescription::Variability()'],['../namespacecoral_1_1model.html#a80178cf2c2d456ee5cccf31028aa799b',1,'coral::model::Variability()']]],
  ['variable',['Variable',['../classcoral_1_1model_1_1_slave_type_description.html#af192152d895fff061af6e4a6d579102c',1,'coral::model::SlaveTypeDescription::Variable()'],['../classcoral_1_1model_1_1_variable_setting.html#ae5b13f7b07392a763c999b171ab16962',1,'coral::model::VariableSetting::Variable()']]],
  ['variable',['Variable',['../classcoral_1_1model_1_1_variable.html',1,'coral::model']]],
  ['variable_5fio_2ehpp',['variable_io.hpp',['../variable__io_8hpp.html',1,'']]],
  ['variabledescription',['VariableDescription',['../classcoral_1_1model_1_1_variable_description.html',1,'coral::model']]],
  ['variableid',['VariableID',['../namespacecoral_1_1model.html#aa6c3f4734047ea5baac0d1c28bbcf5a3',1,'coral::model']]],
  ['variablepublisher',['VariablePublisher',['../classcoral_1_1bus_1_1_variable_publisher.html',1,'coral::bus']]],
  ['variablepublisher',['VariablePublisher',['../classcoral_1_1bus_1_1_variable_publisher.html#a4ff5d1da4b8f015e877188b7b15a516f',1,'coral::bus::VariablePublisher']]],
  ['variables',['Variables',['../classcoral_1_1model_1_1_slave_type_description.html#a0a9c9569499c4d77a7142b956ddd7e01',1,'coral::model::SlaveTypeDescription']]],
  ['variablesetting',['VariableSetting',['../classcoral_1_1model_1_1_variable_setting.html',1,'coral::model']]],
  ['variablesetting',['VariableSetting',['../classcoral_1_1model_1_1_variable_setting.html#a68b6d6425c5aeca3b2cfd379721b4aad',1,'coral::model::VariableSetting::VariableSetting(VariableID variable, const ScalarValue &amp;value)'],['../classcoral_1_1model_1_1_variable_setting.html#ac8da204e837aba5ae45d940d2b37fa6d',1,'coral::model::VariableSetting::VariableSetting(VariableID inputVar, const coral::model::Variable &amp;outputVar)'],['../classcoral_1_1model_1_1_variable_setting.html#ac2287eaa11b03909d725eb869d67d88c',1,'coral::model::VariableSetting::VariableSetting(VariableID inputVar, const ScalarValue &amp;value, const coral::model::Variable &amp;outputVar)']]],
  ['variablesettings',['variableSettings',['../structcoral_1_1master_1_1_slave_config.html#a56f6585e60446634e5e0d6dbc25a9692',1,'coral::master::SlaveConfig']]],
  ['variablesubscriber',['VariableSubscriber',['../classcoral_1_1bus_1_1_variable_subscriber.html',1,'coral::bus']]],
  ['variablesubscriber',['VariableSubscriber',['../classcoral_1_1bus_1_1_variable_subscriber.html#a54652e49799f6a7910ac38c357a58394',1,'coral::bus::VariableSubscriber']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector']]],
  ['vector_3c_20coral_3a_3amodel_3a_3avariablesetting_20_3e',['vector&lt; coral::model::VariableSetting &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20fmi1_5fvalue_5freference_5ft_20_3e',['vector&lt; fmi1_value_reference_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20fmi2_5fvalue_5freference_5ft_20_3e',['vector&lt; fmi2_value_reference_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20coral_3a_3afmi_3a_3aslaveinstance1_20_3e_20_3e',['vector&lt; std::weak_ptr&lt; coral::fmi::SlaveInstance1 &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aweak_5fptr_3c_20coral_3a_3afmi_3a_3aslaveinstance2_20_3e_20_3e',['vector&lt; std::weak_ptr&lt; coral::fmi::SlaveInstance2 &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['version',['Version',['../classcoral_1_1model_1_1_slave_type_description.html#ab4e6609ce9c1a5891300b3c83155a727',1,'coral::model::SlaveTypeDescription']]],
  ['vfprintf',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
